// Function to get current timezone offset
const getTimezoneOffset = (timezone) => {
  try {
    const date = new Date();
    const formatter = new Intl.DateTimeFormat('en-US', {
      timeZone: timezone,
      timeZoneName: 'longOffset'
    });
    
    // Get the timezone parts
    const parts = formatter.formatToParts(date);
    const timezonePart = parts.find(part => part.type === 'timeZoneName');
    return timezonePart.value;
  } catch (error) {
    // Fallback to static UTC+0 if there's an error
    return 'UTC+0';
  }
};

// Function to generate the timezone list with current offsets
export const getDynamicTimezoneList = () => [
  { value: 'Africa/Algiers', label: `West Central Africa (${getTimezoneOffset('Africa/Algiers')})` },
  { value: 'Africa/Cairo', label: `Cairo (${getTimezoneOffset('Africa/Cairo')})` },
  { value: 'Africa/Casablanca', label: `Casablanca (${getTimezoneOffset('Africa/Casablanca')})` },
  { value: 'Africa/Harare', label: `Harare (${getTimezoneOffset('Africa/Harare')})` },
  { value: 'Africa/Johannesburg', label: `Pretoria (${getTimezoneOffset('Africa/Johannesburg')})` },
  { value: 'Africa/Monrovia', label: `Monrovia (${getTimezoneOffset('Africa/Monrovia')})` },
  { value: 'Africa/Nairobi', label: `Nairobi (${getTimezoneOffset('Africa/Nairobi')})` },
  { value: 'America/Argentina/Buenos_Aires', label: `Buenos Aires (${getTimezoneOffset('America/Argentina/Buenos_Aires')})` },
  { value: 'America/Bogota', label: `Bogota (${getTimezoneOffset('America/Bogota')})` },
  { value: 'America/Caracas', label: `Caracas (${getTimezoneOffset('America/Caracas')})` },
  { value: 'America/Chicago', label: `Central Time (US & Canada) (${getTimezoneOffset('America/Chicago')})` },
  { value: 'America/Chihuahua', label: `Chihuahua (${getTimezoneOffset('America/Chihuahua')})` },
  { value: 'America/Denver', label: `Mountain Time (US & Canada) (${getTimezoneOffset('America/Denver')})` },
  { value: 'America/Godthab', label: `Greenland (${getTimezoneOffset('America/Godthab')})` },
  { value: 'America/Guatemala', label: `Central America (${getTimezoneOffset('America/Guatemala')})` },
  { value: 'America/Guyana', label: `Georgetown (${getTimezoneOffset('America/Guyana')})` },
  { value: 'America/Halifax', label: `Atlantic Time (Canada) (${getTimezoneOffset('America/Halifax')})` },
  { value: 'America/Indiana/Indianapolis', label: `Indiana (East) (${getTimezoneOffset('America/Indiana/Indianapolis')})` },
  { value: 'America/Juneau', label: `Paz (${getTimezoneOffset('America/Juneau')})` },
  { value: 'America/Lima', label: `Quito (${getTimezoneOffset('America/Lima')})` },
  { value: 'America/Los_Angeles', label: `Pacific Time (US & Canada) (${getTimezoneOffset('America/Los_Angeles')})` },
  { value: 'America/Mazatlan', label: `Mazatlan (${getTimezoneOffset('America/Mazatlan')})` },
  { value: 'America/Mexico_City', label: `Mexico City (${getTimezoneOffset('America/Mexico_City')})` },
  { value: 'America/Monterrey', label: `Monterrey (${getTimezoneOffset('America/Monterrey')})` },
  { value: 'America/Montevideo', label: `Montevideo (${getTimezoneOffset('America/Montevideo')})` },
  { value: 'America/New_York', label: `Eastern Time (US & Canada) (${getTimezoneOffset('America/New_York')})` },
  { value: 'America/Phoenix', label: `Arizona (${getTimezoneOffset('America/Phoenix')})` },
  { value: 'America/Regina', label: `Saskatchewan (${getTimezoneOffset('America/Regina')})` },
  { value: 'America/Santiago', label: `Santiago (${getTimezoneOffset('America/Santiago')})` },
  { value: 'America/Sao_Paulo', label: `Brasilia (${getTimezoneOffset('America/Sao_Paulo')})` },
  { value: 'America/St_Johns', label: `Newfoundland (${getTimezoneOffset('America/St_Johns')})` },
  { value: 'America/Tijuana', label: `Tijuana (${getTimezoneOffset('America/Tijuana')})` },
  { value: 'Asia/Almaty', label: `Almaty (${getTimezoneOffset('Asia/Almaty')})` },
  { value: 'Asia/Baghdad', label: `Baghdad (${getTimezoneOffset('Asia/Baghdad')})` },
  { value: 'Asia/Baku', label: `Baku (${getTimezoneOffset('Asia/Baku')})` },
  { value: 'Asia/Bangkok', label: `Hanoi (${getTimezoneOffset('Asia/Bangkok')})` },
  { value: 'Asia/Chongqing', label: `Chongqing (${getTimezoneOffset('Asia/Chongqing')})` },
  { value: 'Asia/Colombo', label: `Sri Jayawardenepura (${getTimezoneOffset('Asia/Colombo')})` },
  { value: 'Asia/Dhaka', label: `Dhaka (${getTimezoneOffset('Asia/Dhaka')})` },
  { value: 'Asia/Hong_Kong', label: `Hong Kong (${getTimezoneOffset('Asia/Hong_Kong')})` },
  { value: 'Asia/Irkutsk', label: `Irkutsk (${getTimezoneOffset('Asia/Irkutsk')})` },
  { value: 'Asia/Jakarta', label: `Jakarta (${getTimezoneOffset('Asia/Jakarta')})` },
  { value: 'Asia/Jerusalem', label: `Jerusalem (${getTimezoneOffset('Asia/Jerusalem')})` },
  { value: 'Asia/Kabul', label: `Kabul (${getTimezoneOffset('Asia/Kabul')})` },
  { value: 'Asia/Kamchatka', label: `Kamchatka (${getTimezoneOffset('Asia/Kamchatka')})` },
  { value: 'Asia/Karachi', label: `Karachi (${getTimezoneOffset('Asia/Karachi')})` },
  { value: 'Asia/Kathmandu', label: `Kathmandu (${getTimezoneOffset('Asia/Kathmandu')})` },
  { value: 'Asia/Krasnoyarsk', label: `Krasnoyarsk (${getTimezoneOffset('Asia/Krasnoyarsk')})` },
  { value: 'Asia/Kuala_Lumpur', label: `Kuala Lumpur (${getTimezoneOffset('Asia/Kuala_Lumpur')})` },
  { value: 'Asia/Kuwait', label: `Kuwait (${getTimezoneOffset('Asia/Kuwait')})` },
  { value: 'Asia/Magadan', label: `Magadan (${getTimezoneOffset('Asia/Magadan')})` },
  { value: 'Asia/Muscat', label: `Muscat (${getTimezoneOffset('Asia/Muscat')})` },
  { value: 'Asia/Novosibirsk', label: `Novosibirsk (${getTimezoneOffset('Asia/Novosibirsk')})` },
  { value: 'Asia/Kolkata', label: `New Delhi (${getTimezoneOffset('Asia/Kolkata')})` },
  { value: 'Asia/Rangoon', label: `Rangoon (${getTimezoneOffset('Asia/Rangoon')})` },
  { value: 'Asia/Riyadh', label: `Riyadh (${getTimezoneOffset('Asia/Riyadh')})` },
  { value: 'Asia/Seoul', label: `Seoul (${getTimezoneOffset('Asia/Seoul')})` },
  { value: 'Asia/Shanghai', label: `Beijing (${getTimezoneOffset('Asia/Shanghai')})` },
  { value: 'Asia/Singapore', label: `Singapore (${getTimezoneOffset('Asia/Singapore')})` },
  { value: 'Asia/Taipei', label: `Taipei (${getTimezoneOffset('Asia/Taipei')})` },
  { value: 'Asia/Tashkent', label: `Tashkent (${getTimezoneOffset('Asia/Tashkent')})` },
  { value: 'Asia/Tbilisi', label: `Tbilisi (${getTimezoneOffset('Asia/Tbilisi')})` },
  { value: 'Asia/Tehran', label: `Tehran (${getTimezoneOffset('Asia/Tehran')})` },
  { value: 'Asia/Tokyo', label: `Tokyo (${getTimezoneOffset('Asia/Tokyo')})` },
  { value: 'Asia/Ulaanbaatar', label: `Ulaanbaatar (${getTimezoneOffset('Asia/Ulaanbaatar')})` },
  { value: 'Asia/Urumqi', label: `Urumqi (${getTimezoneOffset('Asia/Urumqi')})` },
  { value: 'Asia/Vladivostok', label: `Vladivostok (${getTimezoneOffset('Asia/Vladivostok')})` },
  { value: 'Asia/Yakutsk', label: `Yakutsk (${getTimezoneOffset('Asia/Yakutsk')})` },
  { value: 'Asia/Yekaterinburg', label: `Yekaterinburg (${getTimezoneOffset('Asia/Yekaterinburg')})` },
  { value: 'Asia/Yerevan', label: `Yerevan (${getTimezoneOffset('Asia/Yerevan')})` },
  { value: 'Atlantic/Azores', label: `Azores (${getTimezoneOffset('Atlantic/Azores')})` },
  { value: 'Atlantic/Cape_Verde', label: `Cape Verde Is. (${getTimezoneOffset('Atlantic/Cape_Verde')})` },
  { value: 'Atlantic/South_Georgia', label: `Mid-Atlantic (${getTimezoneOffset('Atlantic/South_Georgia')})` },
  { value: 'Australia/Adelaide', label: `Adelaide (${getTimezoneOffset('Australia/Adelaide')})` },
  { value: 'Australia/Brisbane', label: `Brisbane (${getTimezoneOffset('Australia/Brisbane')})` },
  { value: 'Australia/Darwin', label: `Darwin (${getTimezoneOffset('Australia/Darwin')})` },
  { value: 'Australia/Hobart', label: `Hobart (${getTimezoneOffset('Australia/Hobart')})` },
  { value: 'Australia/Melbourne', label: `Melbourne (${getTimezoneOffset('Australia/Melbourne')})` },
  { value: 'Australia/Perth', label: `Perth (${getTimezoneOffset('Australia/Perth')})` },
  { value: 'Australia/Sydney', label: `Sydney (${getTimezoneOffset('Australia/Sydney')})` },
  { value: 'Europe/Athens', label: `Athens (${getTimezoneOffset('Europe/Athens')})` },
  { value: 'Europe/Belgrade', label: `Belgrade (${getTimezoneOffset('Europe/Belgrade')})` },
  { value: 'Europe/Berlin', label: `Bern (${getTimezoneOffset('Europe/Berlin')})` },
  { value: 'Europe/Bratislava', label: `Bratislava (${getTimezoneOffset('Europe/Bratislava')})` },
  { value: 'Europe/Brussels', label: `Brussels (${getTimezoneOffset('Europe/Brussels')})` },
  { value: 'Europe/Bucharest', label: `Bucharest (${getTimezoneOffset('Europe/Bucharest')})` },
  { value: 'Europe/Budapest', label: `Budapest (${getTimezoneOffset('Europe/Budapest')})` },
  { value: 'Europe/Copenhagen', label: `Copenhagen (${getTimezoneOffset('Europe/Copenhagen')})` },
  { value: 'Europe/Dublin', label: `Dublin (${getTimezoneOffset('Europe/Dublin')})` },
  { value: 'Europe/Helsinki', label: `Helsinki (${getTimezoneOffset('Europe/Helsinki')})` },
  { value: 'Europe/Istanbul', label: `Istanbul (${getTimezoneOffset('Europe/Istanbul')})` },
  { value: 'Europe/Kiev', label: `Kyiv (${getTimezoneOffset('Europe/Kiev')})` },
  { value: 'Europe/Lisbon', label: `Lisbon (${getTimezoneOffset('Europe/Lisbon')})` },
  { value: 'Europe/Ljubljana', label: `Ljubljana (${getTimezoneOffset('Europe/Ljubljana')})` },
  { value: 'Europe/London', label: `London (${getTimezoneOffset('Europe/London')})` },
  { value: 'Europe/Madrid', label: `Madrid (${getTimezoneOffset('Europe/Madrid')})` },
  { value: 'Europe/Minsk', label: `Minsk (${getTimezoneOffset('Europe/Minsk')})` },
  { value: 'Europe/Moscow', label: `Volgograd (${getTimezoneOffset('Europe/Moscow')})` },
  { value: 'Europe/Paris', label: `Paris (${getTimezoneOffset('Europe/Paris')})` },
  { value: 'Europe/Prague', label: `Prague (${getTimezoneOffset('Europe/Prague')})` },
  { value: 'Europe/Riga', label: `Riga (${getTimezoneOffset('Europe/Riga')})` },
  { value: 'Europe/Rome', label: `Rome (${getTimezoneOffset('Europe/Rome')})` },
  { value: 'Europe/Sarajevo', label: `Sarajevo (${getTimezoneOffset('Europe/Sarajevo')})` },
  { value: 'Europe/Skopje', label: `Skopje (${getTimezoneOffset('Europe/Skopje')})` },
  { value: 'Europe/Sofia', label: `Sofia (${getTimezoneOffset('Europe/Sofia')})` },
  { value: 'Europe/Stockholm', label: `Stockholm (${getTimezoneOffset('Europe/Stockholm')})` },
  { value: 'Europe/Tallinn', label: `Tallinn (${getTimezoneOffset('Europe/Tallinn')})` },
  { value: 'Europe/Vienna', label: `Vienna (${getTimezoneOffset('Europe/Vienna')})` },
  { value: 'Europe/Vilnius', label: `Vilnius (${getTimezoneOffset('Europe/Vilnius')})` },
  { value: 'Europe/Warsaw', label: `Warsaw (${getTimezoneOffset('Europe/Warsaw')})` },
  { value: 'Europe/Zagreb', label: `Zagreb (${getTimezoneOffset('Europe/Zagreb')})` },
  { value: 'Pacific/Apia', label: `Samoa (${getTimezoneOffset('Pacific/Apia')})` },
  { value: 'Pacific/Auckland', label: `Wellington (${getTimezoneOffset('Pacific/Auckland')})` },
  { value: 'Pacific/Chatham', label: `Chatham Is. (${getTimezoneOffset('Pacific/Chatham')})` },
  { value: 'Pacific/Fakaofo', label: `Tokelau Is. (${getTimezoneOffset('Pacific/Fakaofo')})` },
  { value: 'Pacific/Fiji', label: `Fiji (${getTimezoneOffset('Pacific/Fiji')})` },
  { value: 'Pacific/Guadalcanal', label: `Solomon Is. (${getTimezoneOffset('Pacific/Guadalcanal')})` },
  { value: 'Pacific/Guam', label: `Guam (${getTimezoneOffset('Pacific/Guam')})` },
  { value: 'Pacific/Honolulu', label: `Hawaii (${getTimezoneOffset('Pacific/Honolulu')})` },
  { value: 'Pacific/Majuro', label: `Marshall Is. (${getTimezoneOffset('Pacific/Majuro')})` },
  { value: 'Pacific/Midway', label: `Midway Island (${getTimezoneOffset('Pacific/Midway')})` },
  { value: 'Pacific/Noumea', label: `New Caledonia (${getTimezoneOffset('Pacific/Noumea')})` },
  { value: 'Pacific/Pago_Pago', label: `American Samoa (${getTimezoneOffset('Pacific/Pago_Pago')})` },
  { value: 'Pacific/Port_Moresby', label: `Port (${getTimezoneOffset('Pacific/Port_Moresby')})` },
  { value: 'Pacific/Tongatapu', label: `Nuku'alofa (${getTimezoneOffset('Pacific/Tongatapu')})` }
];

// Export the timezone list that will be dynamically generated when imported
export const timezoneList = getDynamicTimezoneList();

