import React from 'react';
import { Box, Typography, IconButton, Tooltip, Skeleton } from '@mui/material';
import { Refresh } from '@mui/icons-material';

const ReportHeader = ({ report, loading, onRefresh }) => {
  return (
    <Box sx={{ mb: 3, p: 2, bgcolor: 'background.paper', borderRadius: 2, boxShadow: 1 }}>
      <Box display="flex" justifyContent="space-between" alignItems="flex-start">
        <Box>
          {loading ? (
            <Box>
              <Skeleton variant="text" width={300} height={28} />
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mt: 1 }}>
                <Skeleton variant="text" width={120} height={22} />
                <Skeleton variant="circular" width={6} height={4} />
                <Skeleton variant="text" width={160} height={22} />
              </Box>
            </Box>
          ) : (
            <Box>
              <Typography variant="h6" color="primary" sx={{ fontWeight: 600 }}>
                {report?.report_type}
              </Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, color: 'text.secondary', my: 0.5 }}>
                <Typography variant="body2" sx={{ fontWeight: 500 }}>
                  Generated by {report?.generated_by}
                </Typography>
                <Box sx={{ width: 3, height: 3, borderRadius: '50%', bgcolor: 'text.disabled' }} />
                <Typography variant="body2">
                  {new Date(report?.generated_at).toLocaleString(undefined, {
                    dateStyle: 'medium',
                    timeStyle: 'short'
                  })}
                </Typography>
                <Typography variant="caption" sx={{ 
                  color: 'text.secondary',
                  display: 'inline-flex',
                  alignItems: 'center',
                  gap: 0.5,
                  bgcolor: 'action.hover',
                  px: 1,
                  py: 0.25,
                  borderRadius: 1
                }}>
                  Version {report?.report_metadata?.report_version}
                </Typography>
              </Box>
            </Box>
          )}
        </Box>
        <Tooltip title="Refresh Report" placement="left">
          <IconButton 
            size="small"
            color="primary"
            onClick={onRefresh}
            disabled={loading}
            sx={{ 
              bgcolor: 'background.default',
              '&:hover': { bgcolor: 'action.hover' },
              transition: 'all 0.2s'
            }}
          >
            <Refresh fontSize="small" />
          </IconButton>
        </Tooltip>
      </Box>
    </Box>
  );
};

export default ReportHeader;