# .github/workflows/windows-build.yml
name: Windows Build

on:
  # Trigger on push to main branch
  push:
    branches: [ main, master ]
  
  # Trigger on pull requests to main branch
  pull_request:
    branches: [ main, master ]
  
  # Allow manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  # Windows Electron Build
  windows-build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Debug Info
      run: |
        echo "Node version:"
        node -v
        echo "NPM version:"
        npm -v
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        dir
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci --verbose
    
    - name: Run linting
      run: |
        echo "Running lint check..."
        npm run lint
    
    - name: Build Electron app for Windows
      run: |
        echo "Building Electron app..."
        npm run electron:build:win --verbose
    
    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-electron-build
        path: dist/
        retention-days: 30